### ISSUE TITLE
Add an algorithm for quick sort

### ISSUE THREAD

**Issue by Princeton21** [Princeton21/Data-Structures-and-Algorithms#15]
Your task is to add quick sort algorithm.

**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**

Submit the algorithm in the [quick_sort](https://github.com/Princeton21/Hacktoberfest_DSA_2021/tree/main/Code/sorting_algorithms/quick_sort) folder.
You can implement this in any language of your preference.

**Comment by Visrutha** [comment]
Hello @Princeton21 ! Can I execute this algorithm in ruby? Can you assign this issue to me?
