### ISSUE TITLE
Add markdown file for stack data structure

### ISSUE THREAD

**Issue by Princeton21** [Princeton21/Data-Structures-and-Algorithms#24]
Your task is to give a detailed explanation of stack.
The explanation should be simple for a beginner to understand.

**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**

Submit the file as  .md file in the [stack](https://github.com/Princeton21/Hacktoberfest_DSA_2021/tree/main/Code/data_structures/stack) folder

**Comment by BhaviniMadhuranath** [comment]
can you assign this task to me?
