### ISSUE TITLE
Add markdown file for queue data structure

### ISSUE THREAD

**Issue by Princeton21** [Princeton21/Data-Structures-and-Algorithms#25]
Your task is to give a detailed explanation of queue.
The explanation should be simple for a beginner to understand.

**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**

Submit the files as a .md file in the [queue](https://github.com/Princeton21/Hacktoberfest_DSA_2021/tree/main/Code/data_structures/queue) folder

**Comment by BhaviniMadhuranath** [comment]
can you assign this to me?
