### ISSUE TITLE
Add Bellman Ford algorithm.

### ISSUE THREAD

**Issue by Princeton21** [Princeton21/Data-Structures-and-Algorithms#396]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error

**Details:**

Implement and add the Bellman-Ford algorithm

**Comment by aryanayush012** [comment]
I want to contribute , Please assign this to me @Princeton21

**Comment by Rakteem007** [comment]
can i contribute to this issue

**Comment by ShubhamShakyawal** [comment]
@Princeton21 Please assign me. I would like to work on this

**Comment by Princeton21** [comment]
> can i contribute to this issue

Sure go ahead.

**Comment by Princeton21** [comment]
> @Princeton21 Please assign me. I would like to work on this

@ShubhamShakyawal The issues are assigned on first come first serve basis
If you want to contribute you are free to create an issue and work on it.

**Comment by ShubhamShakyawal** [comment]
Okay, @Princeton21. I'll create an issue for Dijkstra’s Algorithm

**Comment by Rakteem007** [comment]
solved the issue
