### ISSUE TITLE
Linked List using C++

### ISSUE THREAD

**Issue by niteshjeganathan** [Princeton21/Data-Structures-and-Algorithms#415]

**Comment by niteshjeganathan** [comment]
@Princeton21 Can you assign this to me

**Comment by Princeton21** [comment]
Sure @niteshjeganathan Go ahead

**Comment by Vishesh-Vijay** [comment]
pls assign it to me

**Comment by Vaishnavi-More** [comment]
@Princeton21 Could you please tell me that can I add questions on data structure like array, linked list?
Can you assign it to me?

**Comment by Princeton21** [comment]
> @Princeton21 Could you please tell me that can I add questions on data structure like array, linked list? Can you assign it to me?

No not problem statements.
But you can implement different data structures and its sub-types.👍

**Comment by Vaishnavi-More** [comment]
Please assign this to me!

**Comment by ankitkumar0622** [comment]
Hi can you please assign this task to me.
